/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vS4xKY7bgwzMXr8EGWsxeA

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsuXBsfQ0GLczI } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: uXBsfQ0gLczI/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsuXBsfQ0GLczI
});
